#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitePerformanceViewer.Handler.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public partial class Home : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n\r\n");



WriteLiteral(@"

<!doctype html>
<html>
<head>
<title>ASP.NET Site Performance Viewer</title>

<script type=""text/javascript"" src=""https://www.google.com/jsapi""></script>
<script type=""text/javascript"">
	google.load(""visualization"", ""1"", { packages: [""corechart""] });
</script>


");


            
            #line 19 "..\..\Handler\Views\Home.cshtml"
Write(SitePerformanceViewer.Handler.Helpers.HandlerHelpers.IncludeStyleSheet("/CSS/jquery.dataTables.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 20 "..\..\Handler\Views\Home.cshtml"
Write(SitePerformanceViewer.Handler.Helpers.HandlerHelpers.IncludeStyleSheet("/CSS/Main.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 22 "..\..\Handler\Views\Home.cshtml"
Write(SitePerformanceViewer.Handler.Helpers.HandlerHelpers.IncludeJavaScript("/Scripts/jquery-2.0.3.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 23 "..\..\Handler\Views\Home.cshtml"
Write(SitePerformanceViewer.Handler.Helpers.HandlerHelpers.IncludeJavaScript("/Scripts/jquery.dataTables.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 25 "..\..\Handler\Views\Home.cshtml"
Write(SitePerformanceViewer.Handler.Helpers.HandlerHelpers.IncludeJavaScript("/Scripts/Main.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script type=\"text/javascript\">\r\n\twindow.GetDataUrl = function (url) {\r\n\t\tvar" +
" handlerUrl = \'");


            
            #line 29 "..\..\Handler\Views\Home.cshtml"
               Write(SitePerformanceViewer.Handler.Helpers.HandlerHelpers.HandlerPath);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n\t\treturn handlerUrl + \'?data=\' + url;\r\n\t}\r\n</script>\r\n\r\n</head>\r\n<body>\r\n\r\n<d" +
"iv class=\"body_wrapper\">\r\n\t\r\n\t<form>\r\n\t<div class=\"pages_date_selector\">\r\n\t<labe" +
"l>Show: \r\n\t<select>\r\n\t\t<option value=\"today\">Today</option>\r\n\t\t<option value=\"");


            
            #line 44 "..\..\Handler\Views\Home.cshtml"
            Write(SitePerformanceViewer.Helpers.DateContext.Today.AddDays(-1).ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral(@""">Yesterday</option>
	</select>
	</label>
	</div>
	</form>
	<div class=""pages_table_pane pane col2 loading_data"">
		
	</div>
	<div class=""pane col2"">
		<div class=""distribution_pane pane loading_data"">
		</div>
		<div class=""trend_pane pane loading_data"">
		</div>
	</div>
</div>
</body>
</html>");


        }
    }
}
#pragma warning restore 1591
