#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitePerformanceViewer.Handler.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class Home : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n\r\n");



WriteLiteral(@"

<!doctype html>
<html>
<head>
<title>ASP.NET Site Performance Viewer</title>

<script type=""text/javascript"" src=""https://www.google.com/jsapi""></script>
<script type=""text/javascript"">
	google.load(""visualization"", ""1"", { packages: [""corechart""] });
</script>

");


            
            #line 18 "..\..\Handler\Views\Home.cshtml"
Write(SitePerformanceViewer.Handler.Helpers.HandlerHelpers.IncludeStyleSheet("/CSS/Main.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 19 "..\..\Handler\Views\Home.cshtml"
Write(SitePerformanceViewer.Handler.Helpers.HandlerHelpers.IncludeStyleSheet("/CSS/jquery.dataTables.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 21 "..\..\Handler\Views\Home.cshtml"
Write(SitePerformanceViewer.Handler.Helpers.HandlerHelpers.IncludeJavaScript("/Scripts/jquery-2.0.3.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 22 "..\..\Handler\Views\Home.cshtml"
Write(SitePerformanceViewer.Handler.Helpers.HandlerHelpers.IncludeJavaScript("/Scripts/jquery.dataTables.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 24 "..\..\Handler\Views\Home.cshtml"
Write(SitePerformanceViewer.Handler.Helpers.HandlerHelpers.IncludeJavaScript("/Scripts/Main.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script type=\"text/javascript\">\r\n\twindow.GetDataUrl = function (url) {\r\n\t\tvar" +
" handlerUrl = \'");


            
            #line 28 "..\..\Handler\Views\Home.cshtml"
               Write(SitePerformanceViewer.Handler.Helpers.HandlerHelpers.HandlerPath);

            
            #line default
            #line hidden
WriteLiteral(@"';
		return handlerUrl + '?data=' + url;
	}
</script>

</head>
<body>

<div class=""body_wrapper"">
	<div class=""pages_table_pane pane"">
	<form style=""display:none;"">
	<div class=""pages_date_selector"">
	<label>Show: 
	<select>
		<option value=""today"">Today</option>
		<option value=""");


            
            #line 43 "..\..\Handler\Views\Home.cshtml"
            Write(SitePerformanceViewer.Helpers.DateContext.Today.AddDays(-1).ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("\">Yesterday</option>\r\n\t</select>\r\n\t</label>\r\n\t</div>\r\n\t</form>\r\n\t<div class=\"page" +
"s_table_container\">\r\n\t</div>\r\n\t</div>\r\n\t<div class=\"distribution_pane pane\">\r\n\t<" +
"/div>\r\n\t<div class=\"trend_pane pane\">\r\n\t</div>\r\n</div>\r\n</body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
