#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitePerformanceViewer.Handler.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public partial class PagesTable : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 2 "..\..\Handler\Views\PagesTable.cshtml"

	public SitePerformanceViewer.Handler.ViewModels.PagePerformanceDataViewModel PagePerformanceData { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n");



WriteLiteral(@"
<div class=""pages_table_container loading"">
		
<table>
<thead>
	<tr>
		<th class=""head_page""><span>Page</span></th>
		<th>Count</th>
		<th>Median</th>
		<th>Mean</th>
		<th>Sum</th>
	</tr>
</thead>
<tbody>
<tr class=""selected""><td class=""total"">All Pages</td><td>");


            
            #line 29 "..\..\Handler\Views\PagesTable.cshtml"
                                                    Write(PagePerformanceData.AllPages.Count);

            
            #line default
            #line hidden
WriteLiteral("</td><td>");


            
            #line 29 "..\..\Handler\Views\PagesTable.cshtml"
                                                                                                Write(PagePerformanceData.AllPages.Median);

            
            #line default
            #line hidden
WriteLiteral("</td><td>");


            
            #line 29 "..\..\Handler\Views\PagesTable.cshtml"
                                                                                                                                             Write(PagePerformanceData.AllPages.Mean);

            
            #line default
            #line hidden
WriteLiteral("</td><td>");


            
            #line 29 "..\..\Handler\Views\PagesTable.cshtml"
                                                                                                                                                                                        Write(PagePerformanceData.AllPages.Sum);

            
            #line default
            #line hidden
WriteLiteral("</td></tr>\n");


            
            #line 30 "..\..\Handler\Views\PagesTable.cshtml"
  foreach(var page in PagePerformanceData.Pages) {

            
            #line default
            #line hidden
WriteLiteral(" <tr>\r\n\t<td>");


            
            #line 32 "..\..\Handler\Views\PagesTable.cshtml"
Write(page.PageName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t<td>");


            
            #line 33 "..\..\Handler\Views\PagesTable.cshtml"
Write(page.Count);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t<td>");


            
            #line 34 "..\..\Handler\Views\PagesTable.cshtml"
Write(page.Median);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t<td>");


            
            #line 35 "..\..\Handler\Views\PagesTable.cshtml"
Write(page.Mean);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t<td>");


            
            #line 36 "..\..\Handler\Views\PagesTable.cshtml"
Write(page.Sum);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n </tr>\n");


            
            #line 38 "..\..\Handler\Views\PagesTable.cshtml"
 }

            
            #line default
            #line hidden
WriteLiteral("</tbody>\r\n</table>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
