#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitePerformanceViewer.Handler.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class PagesTable : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 2 "..\..\Handler\Views\PagesTable.cshtml"

	public ICollection<SitePerformanceViewer.Handler.ViewModels.PagePerformanceDataViewModel> PagePerformanceData { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n<table>\r\n<thead>\r\n\t<tr>\r\n\t\t<th>Page</th>\r\n\t\t<th>Count</th>\r\n\t\t<th>Median</th>\r\n" +
"\t\t<th>Average</th>\r\n\t\t<th>Sum</th>\r\n\t</tr>\r\n</thead>\r\n<tbody>\n");


            
            #line 27 "..\..\Handler\Views\PagesTable.cshtml"
  foreach(var page in PagePerformanceData) {

            
            #line default
            #line hidden
WriteLiteral(" <tr>\r\n\t<td>");


            
            #line 29 "..\..\Handler\Views\PagesTable.cshtml"
Write(page.PageName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t<td>");


            
            #line 30 "..\..\Handler\Views\PagesTable.cshtml"
Write(page.Count);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t<td>");


            
            #line 31 "..\..\Handler\Views\PagesTable.cshtml"
Write(page.Mean);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t<td>");


            
            #line 32 "..\..\Handler\Views\PagesTable.cshtml"
Write(page.Median);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t<td>");


            
            #line 33 "..\..\Handler\Views\PagesTable.cshtml"
Write(page.Sum);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n </tr>\n");


            
            #line 35 "..\..\Handler\Views\PagesTable.cshtml"
 }

            
            #line default
            #line hidden
WriteLiteral("</tbody>\r\n</table>");


        }
    }
}
#pragma warning restore 1591
