#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitePerformanceViewer.Handler.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class ResponseDistribution : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 3 "..\..\Handler\Views\ResponseDistribution.cshtml"

	public SitePerformanceViewer.Handler.ViewModels.ResponseDistributionViewModel Buckets{get;set;}

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");


WriteLiteral(@"


<script type=""text/javascript"">
	(function () {
		//google.load(""visualization"", ""1"", { packages: [""corechart""] });
		
		//google.setOnLoadCallback(drawPingChart);


		//drawPingChart();
		function drawPingChart() {
			var tbl = [[""Duration"", ""Count"", ""Cumulative %""]];

			tbl = tbl.concat(");


            
            #line 19 "..\..\Handler\Views\ResponseDistribution.cshtml"
                Write(new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(Buckets.Buckets.Select(b=>new [] { b.MaxExcl,b.Count,b.CumulativePercentage}).ToArray()));

            
            #line default
            #line hidden
WriteLiteral(");\r\n\r\n\t\t\t\r\n\r\n\t\t\t//console.log(tbl);\r\n\r\n\t\t\tvar data = google.visualization.arrayTo" +
"DataTable(tbl);\r\n\r\n\t\t\tdata.addColumn({ type: \'string\', role: \'annotation\' })\r\n\r\n" +
"\t\t\tdata.setValue(");


            
            #line 29 "..\..\Handler\Views\ResponseDistribution.cshtml"
            Write(Buckets.MedianBucketIndex);

            
            #line default
            #line hidden
WriteLiteral(", tbl[0].length, \"50%\");\r\n\t\t\tdata.setValue(");


            
            #line 30 "..\..\Handler\Views\ResponseDistribution.cshtml"
            Write(Buckets._90PctBucketIndex);

            
            #line default
            #line hidden
WriteLiteral(@", tbl[0].length, ""90%"");

			var options = {
				title: 'Distribution',
				series: { 1: { targetAxisIndex: 1 } }
				//vAxis: { logScale: true },
				//legend: { position: ""right"" },
				//chartArea: {
				//	width: ""70%"",
				//	left: 50
				//}
			};

			var chart = new google.visualization.LineChart(document.getElementsByClassName('distribution_chart_container')[0]);
			chart.draw(data, options);
		}
		drawPingChart();
	})();
</script>
<div class=""distribution_chart_container"">

</div>");


        }
    }
}
#pragma warning restore 1591
